import requests
import xml.etree.ElementTree as ET
from datetime import datetime

FEED_URL = "https://medium.com/feed/@USDigitalService"

BLOGS_DIR = "../_medium-blogs"
BLOG_TEMPLATE = '''---
# this file was generated by a script

layout: default
banner_file: banner--people-projects-lg.svg
banner_file_mobile: banner--people-projects-sm.svg
blog_page: true

'''

def get_date_from_pubdate_string(pubdate):
	# sample input: "Mon, 03 Aug 2020 13:31:01 GMT"
	return datetime.strptime(pubdate, "%a, %d %b %Y %H:%M:%S %Z")
	
resp = requests.get(FEED_URL)
root = ET.fromstring(resp.text)
items = root[0].findall('item')

for i in items:
	title = i.find('title').text
	pub_date = i.find('pubDate').text
	pub_date = get_date_from_pubdate_string(pub_date)
	pub_date_str = pub_date.strftime("%Y%m%d")
	
	content = i.find('{http://purl.org/rss/1.0/modules/content/}encoded').text

	filename = "{}/{}_blog.md".format(BLOGS_DIR, pub_date_str)
	with open(filename, 'w') as f:
		f.writelines(BLOG_TEMPLATE)
		f.writelines('title: "{}"\n'.format(title))
		f.writelines('permalink: medium-snapshot/{}\n'.format(pub_date_str))
		f.writelines('pub_date: "{}"\n'.format(pub_date.strftime("%b %-d, %Y")))
		f.writelines("\n---\n")
		f.writelines(content)
